# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'Pokemon Game' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Pokemon Game
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  target 'Pokemon GameTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Pokemon GameUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
